# Generated by Django 5.2.8 on 2025-11-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_cover_url_playlist_spotify_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='song',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='valence',
        ),
    ]
